Online Survey/Models/Answer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Id { get; set; }
        public string PersonCode { get; set; }
        public string PersonName { get; set; }
        public string UserCode { get; set; }
        public string Score { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
    }
}

Online Survey/Controllers/AnswerController.cs
using Online_Survey.Models;
using Online_Survey.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Online_Survey.Controllers
{
    public class AnswerController : BaseController
    {
        public ActionResult Index()
        {
            var model = db.Answer.Where(m => m.UserCode == UserCode).ToList();
            return View(model);
        }
        public ActionResult Create(string Code)
        {
            if (Code == null)
            {
                List<SelectListItem> personList = (from person in db.Person
                                                   where person.Code != UserCode
                                                   select new SelectListItem
                                                   {
                                                       Text = person.NameSurname,
                                                       Value = person.Code.ToString()
                                                   }).ToList();

                ViewBag.Person = new SelectList(personList.OrderBy(m => m.Text), "Value", "Text");

                var questionModel = db.Question.ToList();
                return View(questionModel);
            }
            else
            {
                CalculateScore(Code);
                return RedirectToAction("Index");
            }
        }
        public void CalculateScore(string code)
        {
            double answerYes = 0, answerNo = 0, scoreResult = 0;
            var answer = db.Answer.FirstOrDefault(m => m.PersonCode == code && m.UserCode == UserCode);
            var answerLine = db.AnswerLine.Where(m => m.AnswerId == answer.Id).ToList();

            foreach (var item in answerLine)
            {
                if (item.Answer == Constants.AnswerType.Yes)
                {
                    answerYes++;
                }
                else
                {
                    answerNo++;
                }
            }
            scoreResult = (answerYes / (answerYes + answerNo)) * 100;
            if (scoreResult > 69)
            {
                answer.IsComplete = true;
            }
            else
            {
                answer.IsComplete = false;
            }
            answer.Score = scoreResult.ToString();
            db.SaveChanges();
        }
        public String SendData(AnswerModel answerModel)
        {
            int? month = DateTime.Now.Month;
            var model = db.Answer.FirstOrDefault(m => m.PersonCode == answerModel.Code && m.UserCode == UserCode && m.CreateDate.Value.Month == month);

            if (model != null)
            {
                SaveAnswerLine(model.Id, answerModel.Answer, answerModel.Question);
            }
            else
            {
                Answer answer = new Answer();
                answer.PersonCode = answerModel.Code;
                answer.PersonName = answerModel.NameSurname;
                answer.UserCode = UserCode;
                answer.CreateDate = DateTime.Now;
                answer.CreateBy = NameSurname;

                db.Answer.Add(answer);
                db.SaveChanges();
                SaveAnswerLine(answer.Id, answerModel.Answer, answerModel.Question);
            }
            return "True";
        }
        public void SaveAnswerLine(int answerId, string answer, string question)
        {
            var model = db.AnswerLine.FirstOrDefault(m => m.AnswerId == answerId && m.Question == question);

            if (model != null)
            {
                model.Answer = answer;
                db.SaveChanges();
            }
            else
            {
                AnswerLine answerLine = new AnswerLine();
                answerLine.AnswerId = answerId;
                answerLine.Answer = answer;
                answerLine.Question = question;

                db.AnswerLine.Add(answerLine);
                db.SaveChanges();
            }

        }
        public ActionResult Detail(int? Id)
        {
            var model = db.AnswerLine.Where(m => m.AnswerId == Id).ToList();
            return View(model);
        }
    }
}

Online Survey/Views/Answer/Create.cshtml
@model IEnumerable<Online_Survey.Models.Question>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    int number = 1;
}

<script src="~/Content/assets/js/jquery.min.js"></script>

<div class="card">
    <div class="card-body">
        <div class="card-title text-center">Anket Cevaplama Sayfası</div>
        <hr>
        @using (Html.BeginForm("Create", "Answer"))
        {
            <div class="form-group">
                @Html.DropDownList("Code", (SelectList)ViewBag.Person, "Lütfen Kişi Seçiniz", new { @class = "form-control" })
            </div>

            foreach (var item in Model)
            {
                <input type="hidden" name="@item.QuestionLine" id="Question_@item.Id" value="@item.QuestionLine" />
                <div class="card mb-3">
                    <div class="card-header p-3">@number)  @item.QuestionLine</div>
                    <div class="card-body p-3">
                        <div class="demo-radio-button">
                            <input type="radio" id="Yes_@item.Id" name="Answer_@item.Id" class="radio_@item.Id" value="@Online_Survey.Constants.AnswerType.Yes">
                            <label class="mb-0" for="Yes_@item.Id">@Online_Survey.Constants.AnswerType.Yes</label>

                            <input type="radio" id="No_@item.Id" name="Answer_@item.Id" class="radio_@item.Id" value="@Online_Survey.Constants.AnswerType.No">
                            <label class="mb-0" for="No_@item.Id">@Online_Survey.Constants.AnswerType.No</label>
                        </div>
                    </div>
                </div>

                <script type="text/javascript">
                    $(document).ready(function () {
                        $('.radio_@item.Id').click(function () {
                            var formdata = new FormData();

                            var code = $('#Code').val();
                            formdata.set("Code", code);

                            var namesurname = $('#Code :selected').text();
                            formdata.set("NameSurname", namesurname);


                            var question = $('#Question_@item.Id').val();
                            formdata.set("Question", question);

                            var answer = $('input[name="Answer_@item.Id"]:checked').val();
                            formdata.set("Answer", answer);
                            if (code == "") {
                                $('#warningMessage').modal('show');
                                return;
                            }

                            $.ajax({
                                url: "/Answer/SendData",
                                data: formdata,
                                type: "POST",
                                cache: false,
                                contentType: false,
                                processData: false,
                                success: function (data) {
                                    if (data == "True") {

                                    }
                                },
                                error: function (data) {
                                    alert("Ekleme Sırasında Hata Meydana Geldi!");
                                }
                            });
                        });
                    });
                </script>
                number++;
            }
            <div class="form-group">
                <button type="submit" class="btn btn-primary float-right px-5"><i class="icon-lock"></i>Kaydet</button>
            </div>
        }
    </div>
</div>

<div class="modal fade" id="warningMessage">
    <div class="modal-dialog">
        <div class="modal-content border-warning">
            <div class="modal-header bg-warning">
                <h5 class="modal-title text-white">Uyarı</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Lütfen Kişi Seçiniz</p>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Kapat</button>
            </div>
        </div>
    </div>
</div>

Online Survey/Views/Answer/Detail.cshtml
@model IEnumerable<Online_Survey.Models.AnswerLine>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    int number = 1;
}

<div class="card">
    <div class="card-body">
        <div class="card-title text-center">Anket Cevaplama Sayfası</div>
       
            @foreach (var item in Model)
            {
                <div class="card mb-3">
                    <div class="card-header p-3">@number)  @item.Question</div>
                    <div class="card-body p-3">
                        <div class="demo-radio-button">
                            <label class="mb-0" for="Yes_@item.Id">@item.Answer</label>
                        </div>
                    </div>
                </div>
                number++;
            }
    </div>
</div>

Online Survey/Views/Answer/Index.cshtml
@model IEnumerable<Online_Survey.Models.Answer>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Content/assets/js/jquery.min.js"></script>
<link href="~/Content/assets/plugins/bootstrap-datatable/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<link href="~/Content/assets/plugins/bootstrap-datatable/css/buttons.bootstrap4.min.css" rel="stylesheet" />

<div class="card">
    <div class="row mt-4">
        <div class="col-12 col-lg-6 col-xl-6">
            <div class="card bg-dark">
                <div class="card-body">
                    <a href="/Answer/Create">
                        <div class="media">
                            <div class="media-body text-left">
                                <h4 class="text-white">Anket Cevaplayın</h4>
                                <span class="text-white">Anket Cevaplamak İçin Tıklayın</span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-6 col-xl-6">
            <div class="card bg-pinterest">
                <div class="card-body">
                    <div class="media">
                        <div class="media-body text-left">
                            <h4 class="text-white">@Model.Count()</h4>
                            <span class="text-white">Toplam Anket Sayısı</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="body">
        <div class="table-reponsive">
            <table id="example" class="table table-bordered" cellpadding="0" style="width:100%;">
                <thead>
                    <tr class="bg-dark" style="color:white;">
                        <td>Ad Soyad</td>
                        <td>Code</td>
                        <td>Score</td>
                        <td>Tamamlanma Durumu</td>
                        <td>Eklenme Tarihi</td>
                        <td>Ekleyen Kişi</td>
                        <td>İşlemler</td>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.PersonName</td>
                            <td>@item.PersonCode</td>
                            <td>@item.Score</td>
                            @if (item.IsComplete == true)
                            {
                                <td>@Online_Survey.Constants.AnswerType.Yes</td>
                            }
                            else
                            {
                                <td>@Online_Survey.Constants.AnswerType.No</td>

                            }
                            <td>@item.CreateDate</td>
                            <td>@item.CreateBy</td>
                            <td>
                                <a class="btn btn-dark" href="/Answer/Detail/@item.Id"><i class="fa fa-pencil"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>
</div>

<script src="~/Content/assets/plugins/bootstrap-datatable/js/jquery.dataTables.min.js"></script>
<script src="~/Content/assets/plugins/bootstrap-datatable/js/dataTables.bootstrap4.min.js"></script>
<script src="~/Content/assets/plugins/bootstrap-datatable/js/dataTables.buttons.min.js"></script>

<script type="text/javascript">
    var jQueryCalis = $.noConflict(true);
    (function ($) {
        $(document).ready(function () {
            $('#example').DataTable({
                "lengthMenu": [[50, 50, -1], [50, 50, "Tümü"]],
                "ordering": true,
                "caseInsensitive": false,
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"
                }
            });
            var table = $('#example').DataTable();
            $('#example').show();
        });
    })(jQueryCalis);
</script>